### PR TITLE
Add some styles to index.php

### PR DESCRIPTION
**Pull request by mankutila**

### CODE REVIEW

**Comment by Ilozuluchris** [comment]
@mankutila Good job, a few question though,is there is an reason this was removed from the head and moved to the very end before the closing tag of body
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script>
            $.getJSON("settings.json", function (data) {
                console.log(data);
                $(".only").append(data['team_name']);
                $(".email_label").append("Enter email to join  " + data['team_name']);
            });
        </script>`
Also I made the submit button stand out,please help me review it.

**Comment by mankutila** [comment]
@Ilozuluchris "there is an reason this was removed from the head and moved to the very end before the closing tag of body" 
This is common good practice:) Scripts in `head` block page render until they load. It affects page speed (maybe here it is not so obvious). If it is important, you can leave them in `head`. Fixes #1

**Comment by Ilozuluchris** [comment]
@mankutila Thanks for your help. Happy Hacktoberfest!

**Comment by mankutila** [comment]
Thanks!:)

**Pull request merged**
